export const EventTypes = {
  UPDATE_TODO: 'UPDATE_TODO_EVENT',
  UPDATE_LIST: 'UPDATE_LIST_EVENT',
  LISTS_EMPTY: 'LISTS_EMPTY_EVENT',
  LISTS_EXIST: 'LISTS_EXIST_EVENT',
  ERROR_TODO: 'ERROR_TODO_EVENT',
  ERROR_LIST: 'ERROR_LIST_EVENT'
};
